server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodie-shop?useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=TRUE
    username: root
    password: 1234Asdfcn.
    hikari:
      connection-timeout: 30000 #ms
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DateSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1
mybatis:
  type-aliases-package: com.yinuo.pojo
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers: com.yinuo.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL
